#!/usr/bin/env python

from easyprocess import EasyProcess
from pyvirtualdisplay import Display

print('starting test display')

with Display(visible=True) as disp:
	print("test-display started")
	with EasyProcess(["xmonad-luca"]) as proc:
		proc.wait()
# vim: tabstop=2 shiftwidth=2 noexpandtab ft=python
